name: Add Project Card on Issue Creation

on:
  issues:
    types:
      - opened

jobs:
  add-project-card:
    runs-on: ubuntu-latest
    steps:
      - name: Add Project Card
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo } = context.repo;
            const { number } = context.issue;

            // Replace 'your_project_id' with the actual ID of your project
            const projectId = '1';

            // Create a new project card
            const cardResponse = await context.octokit.projects.createCard({
              column_id: projectId,
              content_id: number,
              content_type: 'Issue'
            });

            console.log(`Project card added: ${cardResponse.data.url}`);